Numpy :--
    NumPy is the core library for scientific computing in Python. It provides a highperformance multidimensional array object, and tools for working with these arrays. It’s a 
successor of Numeric package

In [2]:
# Code for Initializing the numpy array :--
import numpy as np
a = np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [4]:
# Code to print the dimension of an array:-
print(a.shape)
print(a[0])
print(a[1])
print(a[2])



(5,)
1
2
3


In [5]:
#Change the element of an array:-
a[0]=5
a[1]=10
print(a)


[ 5 10  3  4  5]


In [8]:
#Create a rank of two array
b = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(b)
print(b.shape)
print(b)
print(b[0,0] ,b[0,1],b[1,0],b[1,1])


[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)
[[1 2 3 4 5]
 [6 7 8 9 0]]
1 2 6 7


Creating the numpy matrices

In [11]:
#create a 3x3 array of all zeroes
a = np.zeros((3,3))
print(a)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
#Creating a 2x2 array of all ones
a = np.ones((2,2))
print(a)


[[1. 1.]
 [1. 1.]]


In [14]:
#creating a 3x3 constant array
c = np.full((3,3),7)
print(c)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [17]:
#create a 3x3 array filled with random values
d = np.random.random((3 ,3))
print(d)


[[0.33213028 0.68203767 0.74691108]
 [0.64283599 0.10260097 0.34487311]
 [0.61703012 0.33219168 0.75872704]]


In [18]:
#Create a 3x3 identity matrix
e = np.eye(3)
print(e)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
#Convert list to an array
f = np.array([1,2,3,4,5])
print(f)


[1 2 3 4 5]


In [21]:
#arange() will create arrays with regularly incrementing values
g = np.arange(50)
print(g)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [23]:
#Creating an array of tuples and lists
h = np.array([[1,2,3,4.0],[5.0,6.0,8,3.0],(1+1j , 2. , 3. ,2.)])
print(h)


[[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j 8.+0.j 3.+0.j]
 [1.+1.j 2.+0.j 3.+0.j 2.+0.j]]


In [36]:
#Create an array of range with float datatypes
i =np.arange(0, 4.5 , 0.5)


print(i)


[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


In [29]:
# linspace() will create arrays with a specified number of items which are
# spaced equally between the specified beginning and end values

j = np.linspace(2. ,4. , 5)
print(j)


[2.  2.5 3.  3.5 4. ]


In [34]:
# indices() will create a set of arrays stacked as a one-higher
# dimensioned array, one per dimension with each representing variation in that dimension


l = np.indices((2,2))
print(l)

k = np.indices((3,3))
print(k)


l = np.indices((4,4))
print(l)

l = np.indices((10,10))
print(l)

[[[0 0]
  [1 1]]

 [[0 1]
  [0 1]]]
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]
[[[0 0 0 0 0 0 0 0 0 0]
  [1 1 1 1 1 1 1 1 1 1]
  [2 2 2 2 2 2 2 2 2 2]
  [3 3 3 3 3 3 3 3 3 3]
  [4 4 4 4 4 4 4 4 4 4]
  [5 5 5 5 5 5 5 5 5 5]
  [6 6 6 6 6 6 6 6 6 6]
  [7 7 7 7 7 7 7 7 7 7]
  [8 8 8 8 8 8 8 8 8 8]
  [9 9 9 9 9 9 9 9 9 9]]

 [[0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]]]


In [5]:
#Converison of Datatypes
import numpy as np
x = np.array([1,2] , dtype = np.float64)
y = np.array([1.0,2.0] ,dtype = np.int64)
z = np.array([5,6] ,dtype = np.float64)
print(z)
print(x)
print(y)



[5. 6.]
[1. 2.]
[1 2]


In [7]:
#Array Indexing 

#Field Access:---

x = np.zeros((3,3) , dtype = [('a' ,np.int32) , ('b' ,np.int64 , (3,3))])
print("x[a].shape:" , x['a'].shape)
print("x['a'].dtype" , x['a'].dtype)
print("x['b'].shape" , x['b'].shape)
print("x['b'].dtype" , x['b'].dtype)


x[a].shape: (3, 3)
x['a'].dtype int32
x['b'].shape (3, 3, 3, 3)
x['b'].dtype int64


In [11]:
#Basic Slicing:---


x = np.array([5,6,8,7,9,4,3,2,1])


print(x[1:3])
print(x[2:5])




[6 8]
[8 7 9]


In [10]:
#We can use the “dot” function to calculate inner products of vectors or to multiply 
#matrices or multiply a vector by a matrix

import numpy as np
x = np.array([[1,2,3,4] ,[5,6,7,8]])
y = np.array([[8,7,9,5], [4,5,6,8]])

a = np.array([9,10])
b = np.array([11,12])
print(a.dot(b))
print(b.dot(a))



219
219


In [13]:

x=np.array([[1,2],[3,4]])
# Compute sum of all elements
print (np.sum(x))
# Compute sum of each column
print (np.sum(x, axis=0))
# Compute sum of each row
print (np.sum(x, axis=1))

print(x.T)  # Find the transpose of a function

10
[4 6]
[3 7]
[[1 3]
 [2 4]]


In [15]:
#Create a Matrix
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

#Create a vector
v = np.array([1,0,1])

#Create a Empty matrix with same shape
b = np.empty_like(a)


# Add a vector to each row of the matrix
for i in range(3):
    b[i ,:] = a[i ,:] +v
    
print(b)






[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
