Loading the Dataset

In [4]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()
print(iris)
print(digits)


{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [5]:
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [6]:
print(digits.target)


[0 1 2 ... 8 9 8]


In [7]:
print(iris.target)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [8]:
from sklearn.model_selection import train_test_split
X = digits.data
y = digits.target

X_train  , y_train  , x_test ,y_test = train_test_split(X , y , test_size = 0.3 ,random_state = 0)
print(X_train)
print(y_train)
print(x_test)
print(y_test)


[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  7. ... 16.  4.  0.]
 [ 0.  0.  0. ... 12.  8.  0.]
 ...
 [ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  4. ...  0.  0.  0.]
 [ 0.  0.  6. ... 11.  0.  0.]]
[[ 0.  0. 11. ... 13. 16.  8.]
 [ 0.  1. 15. ...  1.  0.  0.]
 [ 0.  2. 13. ... 16. 16.  3.]
 ...
 [ 0.  0.  0. ... 15.  1.  0.]
 [ 0.  0.  8. ...  2.  0.  0.]
 [ 0.  0.  1. ... 11.  1.  0.]]
[9 3 6 ... 7 7 8]
[2 8 2 6 6 7 1 9 8 5 2 8 6 6 6 6 1 0 5 8 8 7 8 4 7 5 4 9 2 9 4 7 6 8 9 4 3
 1 0 1 8 6 7 7 1 0 7 6 2 1 9 6 7 9 0 0 5 1 6 3 0 2 3 4 1 9 2 6 9 1 8 3 5 1
 2 8 2 2 9 7 2 3 6 0 5 3 7 5 1 2 9 9 3 1 7 7 4 8 5 8 5 5 2 5 9 0 7 1 4 7 3
 4 8 9 7 9 8 2 6 5 2 5 8 4 8 7 0 6 1 5 9 9 9 5 9 9 5 7 5 6 2 8 6 9 6 1 5 1
 5 9 9 1 5 3 6 1 8 9 8 7 6 7 6 5 6 0 8 8 9 8 6 1 0 4 1 6 3 8 6 7 4 5 6 3 0
 3 3 3 0 7 7 5 7 8 0 7 8 9 6 4 5 0 1 4 6 4 3 3 0 9 5 9 2 1 4 2 1 6 8 9 2 4
 9 3 7 6 2 3 3 1 6 9 3 6 3 2 2 0 7 6 1 1 9 7 2 7 8 5 5 7 5 2 3 7 2 7 5 5 7
 0 9 1 6 5 9 7 4 3 8 0 3 6 4 6 3 2 6 8 8 8 4 6 7 5 2 4 5 3 2 4 6 9 4 5 4 

In [10]:
from sklearn.linear_model import LinearRegression

clf = LinearRegression()

X , y = digits.data[:-10] , digits.data[:-10]

clf.fit(X , y)

clf.predict(X[0].reshape(1 , -1))



array([[ 0.00000000e+00,  4.17634677e-16,  5.00000000e+00,
         1.30000000e+01,  9.00000000e+00,  1.00000000e+00,
        -2.15973073e-15, -1.57946572e-15, -1.06913176e-15,
         5.56174030e-15,  1.30000000e+01,  1.50000000e+01,
         1.00000000e+01,  1.50000000e+01,  5.00000000e+00,
        -1.70089637e-15,  5.59018028e-16,  3.00000000e+00,
         1.50000000e+01,  2.00000000e+00, -7.40033035e-15,
         1.10000000e+01,  8.00000000e+00,  2.35922393e-16,
        -8.01394812e-17,  4.00000000e+00,  1.20000000e+01,
        -4.28151438e-15,  8.36136715e-16,  8.00000000e+00,
         8.00000000e+00, -9.64668883e-17,  0.00000000e+00,
         5.00000000e+00,  8.00000000e+00, -7.44066267e-15,
         1.85528676e-15,  9.00000000e+00,  8.00000000e+00,
         0.00000000e+00,  2.72371915e-16,  4.00000000e+00,
         1.10000000e+01,  1.08177356e-14,  1.00000000e+00,
         1.20000000e+01,  7.00000000e+00,  4.13948389e-16,
         3.28919834e-16,  2.00000000e+00,  1.40000000e+0